import Layout from "../components/layout";
import Head from "next/head";
import { TOKEN, DATABASE_ID_PHOTOS } from "../config/index";
import PhotoItem from "../components/photos/photo-item";

export default function Photos({ photos }) {
  console.log("projects", photos);
  return (
    <>
      <Layout>
        <div className="flex flex-col items-center justify-center min-h-screen px-6 py-10 mb-10">
          <Head>
            <title>Centum_Joonho_Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <h1>
            Total photos:
            <span className="pl-4 text-blue-500">{photos.results.length}</span>
          </h1>

          <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
            {photos.results &&
              photos.results.map((aPhoto) => (
                <PhotoItem key={aPhoto.id} data={aPhoto} />
              ))}
          </div>
        </div>
      </Layout>
    </>
  );
}
//빌드 타임에 호출 !  딱 1번
export async function getStaticProps() {
  const options = {
    method: "POST",
    headers: {
      accept: "application/json",
      "Notion-Version": "2022-06-28",
      "content-type": "application/json",
      Authorization: `Bearer ${TOKEN}`,
    },
    body: JSON.stringify({
      sorts: [
        {
          property: "Name",
          direction: "ascending",
        },
      ],
      page_size: 100,
    }),
  };

  const res = await fetch(
    `https://api.notion.com/v1/databases/${DATABASE_ID_PHOTOS}/query`,
    options
  );
  const photos = await res.json();
  return {
    props: { photos }, // will be passed to the page component as props
  };
}
